using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment3.Models
{
    public class Organization
    {
        /// <summary>
        /// Autogenerated, ID of the organization
        /// </summary>
        [Key]
        public Guid Id { get; set; }

        /// <summary>
        /// Autogenerated, time at which the record was created
        /// </summary>
        [Required]
        public DateTimeOffset CreationTime { get; set; }

        /// <summary>
        /// Name of the organization
        /// </summary>
        [Required]
        [StringLength(256)]
        public string Name { get; set; }

        /// <summary>
        /// Type of the organization
        /// </summary>
        [Required]
        [RegularExpression("Hospital|Clinic|Pharmacy", ErrorMessage = "Type must be one of Hospital, Clinic or Pharmacy")]
        public string Type { get; set; }

        /// <summary>
        /// Address of the organization
        /// </summary>
        [Required]
        public string Address { get; set; }
    }
}
