using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Assignment3.Models
{
    public class Patient
    {
        /// <summary>
        /// Autogenerated, ID of the patient
        /// </summary>
        [Key]
        public Guid Id { get; set; }

        /// <summary>
        /// Autogenerated, time at which the record was created
        /// </summary>
        [Required]
        public DateTimeOffset CreationTime { get; set; }

        /// <summary>
        /// First name of the patient
        /// </summary>
        [Required]
        [StringLength(128)]
        public string FirstName { get; set; }

        /// <summary>
        /// Last name of the patient
        /// </summary>
        [Required]
        [StringLength(128)]
        public string LastName { get; set; }

        /// <summary>
        /// Date of birth of the patient
        /// </summary>
        [Required]
        public DateTimeOffset DateOfBirth { get; set; }
    }
}
